name: upcom-learn-demo
version: 0.1.0
authors:
- Mike Lewis <mike@updroid.com>
description: UpCom Tab for a collection of lessons in robotics.
homepage: https://www.updroid.com/upcom
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
  upcom-api:
    path: ../upcom-api
